# Java Gradle CircleCI 2.1 configuration file
version: 2.1
description: |
    Build and test a simple Java project using Gradle.
display:
    home_url: https://gradle.org/
    source_url: https://github.com/CircleCI-Public/gradle-orb
orbs:
  gradle: circleci/gradle@3.0.0
jobs:
  say_workflow_starting:
    docker:
      - image: cimg/openjdk:11.0.13
    steps:
      - run: echo "CircleCI Workflow starting"
      - run: java --version
      - run: gradle -v
  say_workflow_ending:
    docker:
      - image: cimg/openjdk:11.0.13
    steps:
      - run: echo "CircleCI Workflow ending."
  checkout-build-test:
    docker:
      - image: cimg/openjdk:11.0.13
    steps:
      - checkout
      - run: gradle build
      - run: gradle test
      # - run: gradle test 
workflows:
    # Build and test a simple Java project using Gradle.
  run_jobs:
    # List of jobs that will run
    jobs:
      - say_workflow_starting
      - checkout-build-test  
      - say_workflow_ending